<header class="main-header">
    <div class="main-wrapper">
        <nav class="main-navigation flex-container">
            <a href="#" class="main-header-logo">Охранное агенство "Д.Е.К.С"</a>
            <ul class="site-navigation flex-container">
                <li class="site-navigation-item site-navigation-current">О нас</li>
                <li class="site-navigation-item site-navigation-current">Услуги</li>
                <li class="site-navigation-item site-navigation-current">Контакты</li>
            </ul>
            <input type="search" class="search">
        </nav>
        <div class="header-bottom">
            <img src="/img/kharkov.jpg" alt="Харьков" class="header-bottom-img">
        </div>
    </div>
</header>
